[colors.primary]
background = "#262626"
foreground = "#c0b18b"

[colors.selection]
background = "#d75f5f"
text = "#2f2f2f"

[font]
normal = { family = "Iosevka", style = "Regular" }
size = 10

# [ui]
# confirm_close = false

[window]
decorations = "none"
opacity = 1.0
