[colors.primary]
background = "#262626"
foreground = "#c0b18b"

[colors.selection]
background = "#d75f5f"
text = "#2f2f2f"

[font]
size = 14.0

[font.normal]
family = "Iosevka Fixed"

[ui]
confirm_close = false

[window]
decorations = "none"
opacity = 1.0
