[language.python]
filetypes = ["python"]
roots = ["requirements.txt", "setup.py", ".git", ".hg"]
command = "pylsp"
offset_encoding = "utf-8"

[language.markdown]
filetypes = ["markdown"]
roots = [".md"]
command = "mdpls"
settings = { markdown = { preview = { auto = true }}}

