# config.toml

# theme = "catppuccin_latte" # light mode
theme = "darkvoid" # dark mode

[editor]
line-number = "absolute"
bufferline = "always"
text-width = 120
rulers = [120]
true-color = true
cursorline = true
end-of-line-diagnostics = "warning"
continue-comments = false
auto-format	= true
default-yank-register = "+"
completion-timeout = 5
color-modes = true
popup-border = "all"
# rainbow-brackets = true
# clipboard-provider = "x-sel"

[editor.soft-wrap]
enable = true

[editor.statusline]
left = ["mode", "spinner"] 
center = ["version-control", "spacer", "separator", "file-name"]
right = ["diagnostics", "separator", "selections", "position", "register", "separator", "file-encoding", "file-type"]
separator = "│"
mode.normal = "NOR"
mode.insert = "INS"
mode.select = "SEL"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
character = "╎"
render = true
skip-levels = 1

[editor.inline-diagnostics]
cursor-line = "warning"

[editor.file-picker]
hidden = false

[editor.gutters]
layout = ["diff", "diagnostics", "line-numbers", "spacer"]

##### KEYBINDS #####
[keys.insert.j]
k = "normal_mode" # Maps `jk` to exit insert mode

[keys.normal]
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"
pageup = "no_op"
pagedown = "no_op"
home = "no_op"
end = "no_op"

C-space = "code_action"
A-space = ":lsp-workspace-command"
C-e = "file_explorer_in_current_directory" # Open the file explorer
C-f = "file_picker_in_current_directory" # Open the file picker
C-b = "buffer_picker" # Open buffer picker
C-v = "toggle_comments" # Toggle comment
C-j = "jumplist_picker" # Jump list picker
C-h = ":bp" # Goto previous buffer
C-l = ":bn" # Goto next buffer
C-x = ":bc" # Close current buffer
C-t = ":sh wezterm start --always-new-process" # Open a new terminal in the current buffer location
S-y = ":yank-diagnostic"
C-g = [
  ":write-all",
  ":insert-output gitui >/dev/tty",
  ":redraw",
  ":set mouse false",
  ":set mouse true",
  ":reload-all"
]
C-y = [
  ':sh rm -f /tmp/unique-file',
  ':insert-output yazi "%{buffer_name}" --chooser-file=/tmp/unique-file',
  ':insert-output echo "\x1b[?1049h\x1b[?2004h" > /dev/tty',
  ':open %sh{cat /tmp/unique-file}',
  ':redraw',
]
S-g = [
  ':sh xdg-open "$(git remote get-url origin)"'
]
"space" = { l =  { p = ":sh latex-preview %{buffer_name}", c = ":sh latexmk -c %{buffer_name}" } }

[keys.insert]
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"
pageup = "no_op"
pagedown = "no_op"
home = "no_op"
end = "no_op"

C-space = "code_action"
C-e = "file_explorer_in_current_directory" # Open the file explorer
C-f = "file_picker_in_current_directory" # Open the file picker
C-b = "buffer_picker" # Open buffer picker
C-v = "toggle_comments" # Toggle comment
# C-g = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw"] # Open lazygit
C-h = ":bp" # Goto previous buffer
C-l = ":bn" # Goto next buffer
C-x = ":bc" # Close current buffer

