# theme = "darkvoid"
theme = "onedarker"

[editor]
line-number = "absolute"
bufferline = "always"
text-width = 100
rulers = [100]
true-color = true
cursorline = true
end-of-line-diagnostics = "warning"
continue-comments = false
auto-format	= true
# clipboard-provider = "x-sel"

[editor.soft-wrap]
enable = true

[editor.statusline]
left = ["mode", "spinner", "version-control", "file-name"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
character = "╎"
render = true

[editor.inline-diagnostics]
cursor-line = "warning"

[editor.file-picker]
hidden = false

[keys.insert.j]
k = "normal_mode" # Maps `jk` to exit insert mode

[keys.normal]
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"
pageup = "no_op"
pagedown = "no_op"
home = "no_op"
end = "no_op"

C-space = "code_action"
C-e = "file_explorer" # Open the file explorer
C-f = "file_picker" # Open the file picker
C-b = "buffer_picker" # Open buffer picker
C-v = "toggle_comments" # Toggle comment
C-j = "jumplist_picker" # Jump list picker
C-h = ":bp" # Goto previous buffer
C-l = ":bn" # Goto next buffer
C-x = ":bc" # Close current buffer
C-t = ":sh wezterm start --always-new-process" # Open a new terminal in the current buffer location
# C-y = ":sh open-yazi"
# C-g = ":sh open-lazygit"
S-y = ":yank-diagnostic"
C-g = [
  ":write-all",
  ":insert-output lazygit >/dev/tty",
  ":redraw",
  ":set mouse false",
  ":set mouse true",
  ":reload-all"
]
C-y = [
  ':sh rm -f /tmp/unique-file',
  ':insert-output yazi "%{buffer_name}" --chooser-file=/tmp/unique-file',
  ':insert-output echo "\x1b[?1049h\x1b[?2004h" > /dev/tty',
  ':open %sh{cat /tmp/unique-file}',
  ':redraw',
]

[keys.insert]
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"
pageup = "no_op"
pagedown = "no_op"
home = "no_op"
end = "no_op"

C-space = "code_action"
C-e = "file_explorer" # Open the file explorer
C-f = "file_picker" # Open the file picker
C-b = "buffer_picker" # Open buffer picker
C-v = "toggle_comments" # Toggle comment
# C-g = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw"] # Open lazygit
C-h = ":bp" # Goto previous buffer
C-l = ":bn" # Goto next buffer
C-x = ":bc" # Close current buffer

